### ISSUE TITLE
react-router

### ISSUE THREAD

**Issue by EricForgy** [ulrikaugustsson/azure-appservice-static#3]
Hi,

Thanks for this repo. It was a HUGE help to me. I am a newbie and with the help of this repo, I was able to deploy the default create-react-app to Azure. Yay!

However, I then added react-router and added one simple route "/hello" to the default CRA. It works fine when I enter `http://localhost:5000/hello`, but now when I deploy this to Azure, I get an error if I access `http://myapp.azurewebsites.net/hello`.

`The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

I've been staring at this more than 24 hours so far :(

After a bunch of research, I think this is due to rewrites, but I thought your web.config was supposed to help with that.

I just pushed a sample here: https://github.com/EricForgy/landing-page

You can see this is just a default create-react-app app with a few minor revisions:

In package.json, I added:

~~~json
    "history": "^4.6.1",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0"
~~~

I modified index.js:

~~~js
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router, Route } from 'react-router-dom'
import createBrowserHistory from 'history/createBrowserHistory'
import App from './App';
import Hello from './Hello.js';
import './index.css';

const history = createBrowserHistory()

ReactDOM.render(
  <Router history={history} >
    <div>
      <Route exact path="/" component={App} />
      <Route path="/hello" component={Hello} />
    </div>
  </Router>,
  document.getElementById('root')
);
~~~

My Hello.js is very simple:

~~~js
import React, { Component } from 'react';

class Hello extends Component {

    render() {
        return (
            <div>
                Hello
            </div>
        );
    }
}

export default Hello
~~~

As I said, it works fine on localhost, but it does not work when I deploy to Azure. I think it should be something to do with web.config, but I'm out of my depth and desperate at this point.

Any ideas? 🙏

**Comment by ulrikaugustsson** [comment]
I can have a look att this in a few hours when I get to a computer. I thought I had this working...

**Comment by EricForgy** [comment]
Thanks! 🙏 

It is most likely me doing something wrong.

I am using Azure App Services and using its built-in Kudu capability to sync with a VSTS repo. The deployment and syncing seems to be working fine and I can access `http://myapp.azurewebsites.net` with no problem, but trying to access `/hello` is not working.

It could also be some config I'm missing in the portal 🤔

**Comment by EricForgy** [comment]
I looks like Kudu did not copy over web.config. I can see it in `D:\home\site\repository`, but it is not in `D:\home\site\wwwroot`. Will try to move that over 🙏

**Comment by EricForgy** [comment]
It works! Sorry for the noise 😅 

Now I need to figure out how to tell Kudu to NOT ignore web.config when copying files and I'll be golden. 

Thank you again 👍

**Comment by ulrikaugustsson** [comment]
I should probably look into that. This sounds like something that I have not fixed properly.

**Comment by EricForgy** [comment]
I think Kudu made a decision intentionally NOT to sync the web.config and I haven't found an option yet to tell it to do so.

However, another way it might work is to add a step to the deployment script to copy web.config from D:\home\site\repository to D:\home\site\wwwroot. 

~~~
# 3. KuduSync
if [[ "$IN_PLACE_DEPLOYMENT" -ne "1" ]]; then
  "$KUDU_SYNC_CMD" -v 50 -f "$DEPLOYMENT_SOURCE/build" -t "$DEPLOYMENT_TARGET" -n "$NEXT_MANIFEST_PATH" -p "$PREVIOUS_MANIFEST_PATH" -i ".git;.hg;.deployment;deploy.sh"

# Add a copy web.config here

  exitWithMessageOnError "Kudu Sync failed"
fi
~~~

What do you think?

**Comment by ulrikaugustsson** [comment]
That is probably the correct solution. ☺️
