### ISSUE TITLE
Gets stuck building.

### ISSUE THREAD

**Issue by dwjohnston** [ulrikaugustsson/azure-appservice-static#5]
This doesn't work for me - it just gets stuck at 'building'.

**Comment by ulrikstrid** [comment]
Any more info?

Also this should probably be deprecated in favour of hosting with the new Azure Storage capabilities.

**Comment by dwjohnston** [comment]
Hi - sorry - that' wasn't very useful. I'll see if I can get back to this with a real basic example. But I gave up with Azure coz free tier doesn't allow custom domains.
